// End-to-end CDP verification harness.
//
// Runs the BUILT MCP code (dist/) against the VENDORED 26.727 browser-client,
// bypassing Cursor's MCP process entirely (same native pipe, separate session).
// Proves: client loads, config shim satisfies the full-CDP gate, the cdp tab
// capability is injected, cdp_send auto-attaches the debugger, commands return
// results, and cdp_events delivers buffered events.
//
// Usage: node verify-cdp.mjs

process.env.CODEX_CHROME_CLIENT =
  "G:/cursor/codex-chrome-mcp/vendor/chrome-26.727.51351/scripts/browser-client.mjs";
process.env.CODEX_CHROME_SESSION_NAME = "🧪 CDP verify";

const { callTool } = await import("./dist/server.js");

function textOf(result) {
  return result.content
    .filter((c) => c.type === "text")
    .map((c) => c.text)
    .join("\n");
}

async function step(label, name, args) {
  process.stdout.write(`\n=== ${label} ===\n`);
  try {
    const res = await callTool(name, args ?? {});
    const out = textOf(res);
    console.log(out.length > 1500 ? out.slice(0, 1500) + " ...[truncated]" : out);
    return { ok: true, out };
  } catch (err) {
    console.log("ERROR: " + (err instanceof Error ? err.message : String(err)));
    return { ok: false, out: String(err) };
  }
}

const summary = {};

// 1. Session + tab
summary.name_session = (await step("1. name_session", "name_session", { name: "🧪 CDP verify" })).ok;
const tabRes = await step("2. new_tab -> example.com", "new_tab", { url: "https://example.com" });
summary.new_tab = tabRes.ok;
if (!tabRes.ok) {
  console.log("\nFATAL: cannot create tab; aborting.");
  process.exit(1);
}

// 2. Is the cdp capability advertised on the tab?
const capRes = await step(
  "3. tab.capabilities.list()",
  "browser_exec",
  { code: "return await tab.capabilities.list();" },
);
summary.cdp_capability_advertised = capRes.ok && /"?cdp"?/.test(capRes.out);

// 3. Take an events cursor BEFORE generating activity.
const ev0 = await step("4. cdp_events (initial cursor)", "cdp_events", { limit: 1 });
summary.cdp_events_initial = ev0.ok;
let cursor;
try {
  cursor = JSON.parse(ev0.out).cursor;
} catch {
  /* leave undefined */
}
console.log("initial cursor =", cursor);

// 4. Raw CDP commands (auto-attach happens extension-side).
const enable = await step("5. cdp_send Page.enable", "cdp_send", { method: "Page.enable" });
summary.cdp_send_page_enable = enable.ok;

const evalRes = await step(
  "6. cdp_send Runtime.evaluate(document.title)",
  "cdp_send",
  { method: "Runtime.evaluate", params: { expression: "document.title", returnByValue: true } },
);
summary.cdp_send_runtime_evaluate = evalRes.ok && /Example Domain/i.test(evalRes.out);

const reload = await step("7. cdp_send Page.reload", "cdp_send", { method: "Page.reload" });
summary.cdp_send_page_reload = reload.ok;

// 5. Read events generated by the reload from the earlier cursor.
const ev1 = await step(
  "8. cdp_events (after reload, from cursor)",
  "cdp_events",
  cursor != null ? { after_sequence: cursor, timeout_ms: 8000 } : { timeout_ms: 8000 },
);
summary.cdp_events_received = ev1.ok && /Page\.|Runtime\.|Target\./.test(ev1.out);

// 6. Clean up: close the test tab.
summary.finalize = (await step("9. finalize (drop test tab)", "finalize", {})).ok;

console.log("\n=== SUMMARY ===");
for (const [k, v] of Object.entries(summary)) console.log(`${v ? "PASS" : "FAIL"}  ${k}`);
const allPass = Object.values(summary).every(Boolean);
console.log(allPass ? "\nALL CHECKS PASSED" : "\nSOME CHECKS FAILED");
process.exit(allPass ? 0 : 1);
